# Host ip for growtopia server
host: "127.0.0.1"

# Port to use for growtopia server
port: 17091

# Options for the webserver
web:
  # Whether or not to automatically create the webserver for the Server
 # autoStart: true
  autoStart: false
  # The port to use
  port: 80

# ENet Server Config
server:
  # Maximum number of peers that should be allocated for the host
  peer: 32

  # The maximum number of channels allowed; if 0, then this is equivalent to ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT 
  channelLimit: 0

  # Downstream bandwidth of the host in bytes/second; if 0, ENet will assume unlimited bandwidth. 
  incomingBandwidth: 0

  # Upstream bandwidth of the host in bytes/second; if 0, ENet will assume unlimited bandwidth.
  outgoingBandwidth: 0